= Apache TomEE Training: Base Lab Kit
Tomitribe
// Settings:
:icons: font
:toc: preamble
:toclevels: 1
ifdef::env-github[:!toc-title:]
// URIs:
:uri-arquillian: http://arquillian.org
:uri-tomee: http://tomee.apache.org
:uri-tomee-maven: http://tomee.apache.org/tomee-maven-plugin.html

This is the base, work-in-progress lab kit for the Apache TomEE training.
The training leverages the combination of {uri-arquillian}[Arquillian] and {uri-tomee}[Apache TomEE 7] as a learning device to study how Java EE 7 works.

== Motivation

Arquillian executes each test method inside a real container (in our case, {uri-tomee}[Apache TomEE]).
You define the deployment archive in the test case, so you have full control over the scenario you want to test (or break).
This is where theory turns into practice.

Arquillian is ideal for this phase of learning because it provides a tight loop of experimentation.
It allowing you to focus on how components are defined, resolved, and executed without having to mess around with (or messing up) the details of creating and deploying an application.
You can start at any point in your application and study how the components are managed and how they interact.

This setup also allows you to set a breakpoint anywhere in the source and unleash the debugger on that line when the tests run.
As a bonus, you can even poke around inside the container.

Follow the rules to discover what works.
Break the rules to discover what doesn't work (or works when you don't expect it to).
*Don't be afraid to experiment!*

Using this approach, you'll be able to quickly become familiar with Java EE, what works, what doesn't work, and be ready to start putting it into practice.

////
Additional defenses:
- Easier to maintain modular labs than a large, monolithic application
- Easier to explore specific scenarios by taking a modular approach (don't all have to tie in)
////

== Overview

This project provides a Java EE 7 web application (war) with a Maven build.
To start, it contains two Java classes:

- link:src/main/java/com/tomitribe/training/setup/PingServlet.java[PingServlet.java] -- A Servlet (accessible at the context path `/ping`) to verify the web application is deployed. 
- link:src/test/java/com/tomitribe/training/setup/ApparatusTest.java[ApparatusTest.java] -- An Arquillian test case to demonstrate Arquillian is working properly with TomEE Embedded.

Where it goes from there is up to you.

== Setup

=== Importing the project into an IDE

We recommend that you import the Maven project into your IDE (i.e., IntelliJ IDEA Ultimate or Eclipse IDE for Java EE Developers).
You'll unlock the most functionality by importing the Maven project since it provides access to profiles that can be used to run the test on different containers.

== Usage

=== Running the tests in the IDE

Once the project is imported, you can navigate to the test case, ApparatusTest, and run it just like you would any JUnit test.
//If it passes then everything is working correctly!
If it passes, you're ready to start testing!

=== Running the tests using Maven

To run the tests in a terminal on TomEE (embedded mode) using Maven, simply run:

 $ mvn test

To run the tests in a terminal on TomEE (managed mode) using Maven, simply run:

 $ mvn test -Parquillian=tomee.managed

== Additional tools

=== Building a local TomEE installation using Maven

You can use this project to generate a TomEE installation.
This functionality is provided by the {uri-tomee-maven}[TomEE Maven plugin].
Simply run the following command from a terminal:

 $ mvn tomee:build -Dtomee-plugin.skipCurrentProject=true

The server will be extracted to the path [.path]_servers/apache-tomee-webprofile-7.0.2_.
You can move this folder a location where you want TomEE installed.

TIP: Use the properties at the bottom of [.path]_pom.xml_ to download a different TomEE profile (e.g., plus) or version.
